//
//  AllPresenter.swift
//  SCBFirstAssignment
//
//  Created by Thapakorn Tuwaemuesa on 30/8/2562 BE.
//  Copyright (c) 2562 SCB. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AllPresentationLogic
{
  func presentSomething(response: All.Something.Response)
}

class AllPresenter: AllPresentationLogic
{
  weak var viewController: AllDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: All.Something.Response)
  {
    let viewModel = All.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
