//
//  FavouriteInteractor.swift
//  SCBFirstAssignment
//
//  Created by Thapakorn Tuwaemuesa on 30/8/2562 BE.
//  Copyright (c) 2562 SCB. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FavouriteBusinessLogic
{
  func doSomething(request: Favourite.Something.Request)
}

protocol FavouriteDataStore
{
  //var name: String { get set }
}

class FavouriteInteractor: FavouriteBusinessLogic, FavouriteDataStore
{
  var presenter: FavouritePresentationLogic?
  var worker: FavouriteWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Favourite.Something.Request)
  {
    worker = FavouriteWorker()
    worker?.doSomeWork()
    
    let response = Favourite.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
